jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: ${{ matrix.java_version }}
    - continue-on-error: true
      env:
        cache-name: maven-cache
      name: Maven cache
      uses: actions/cache@v3
      with:
        key: build-${{ env.cache-name }}
        path: ~/.m2
    - continue-on-error: true
      name: oracle
      run: mvn -T 8 clean test -Dprops.file=testconfig/ebean-oracle.properties
    strategy:
      fail-fast: false
      matrix:
        java_version:
        - 11
        os:
        - ubuntu-latest
name: Oracle
on:
  repository_dispatch:
    types: trigger-ga___oracle.yml
